export interface HeritageProduct {
  sku: string;
  heritageNumber: string;
  name: string;
  category: string;
  subcategory: string;
  price: number;
  unit: string;
  manufacturer: string;
  description?: string;
}

export const HERITAGE_CATEGORIES = [
  'Pumps',
  'Filters',
  'Heaters',
  'Automation',
  'Valves',
  'Chemicals',
  'Cleaners',
  'Lighting',
  'Covers',
  'Safety',
  'Plumbing',
  'Motors',
  'Parts',
  'Tools',
  'Labor',
] as const;

export type HeritageCategory = typeof HERITAGE_CATEGORIES[number];

export const HERITAGE_PRODUCTS: HeritageProduct[] = [
  // PUMPS - Variable Speed (50 products)
  { sku: 'PUMP-VS-001', heritageNumber: 'HAY-342032', name: 'Hayward TriStar VS 950', category: 'Pumps', subcategory: 'Variable Speed', price: 1849.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-VS-002', heritageNumber: 'HAY-342033', name: 'Hayward TriStar VS 900', category: 'Pumps', subcategory: 'Variable Speed', price: 1649.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-VS-003', heritageNumber: 'PEN-011018', name: 'Pentair IntelliFlo VSF 3HP', category: 'Pumps', subcategory: 'Variable Speed', price: 1899.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-VS-004', heritageNumber: 'PEN-011028', name: 'Pentair IntelliFlo VS+SVRS', category: 'Pumps', subcategory: 'Variable Speed', price: 1749.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-VS-005', heritageNumber: 'PEN-011057', name: 'Pentair IntelliFlo3 VSF', category: 'Pumps', subcategory: 'Variable Speed', price: 2149.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-VS-006', heritageNumber: 'JAN-VSSHP270', name: 'Jandy VS-FloPro 2.7HP', category: 'Pumps', subcategory: 'Variable Speed', price: 1549.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'PUMP-VS-007', heritageNumber: 'JAN-VSFHP165', name: 'Jandy ePump 1.65HP VS', category: 'Pumps', subcategory: 'Variable Speed', price: 1299.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'PUMP-VS-008', heritageNumber: 'STA-343001', name: 'Sta-Rite IntelliPro VSF', category: 'Pumps', subcategory: 'Variable Speed', price: 1699.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'PUMP-VS-009', heritageNumber: 'HAY-SP3202VSP', name: 'Hayward MaxFlo VS 500', category: 'Pumps', subcategory: 'Variable Speed', price: 1249.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-VS-010', heritageNumber: 'HAY-SP2602VSP', name: 'Hayward Super Pump VS 700', category: 'Pumps', subcategory: 'Variable Speed', price: 1349.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-VS-011', heritageNumber: 'PEN-342001', name: 'Pentair SuperFlo VS', category: 'Pumps', subcategory: 'Variable Speed', price: 1099.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-VS-012', heritageNumber: 'PEN-342002', name: 'Pentair SuperFlo VS 1.5HP', category: 'Pumps', subcategory: 'Variable Speed', price: 1149.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-VS-013', heritageNumber: 'HAY-SP3400VSP', name: 'Hayward EcoStar VS', category: 'Pumps', subcategory: 'Variable Speed', price: 1799.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-VS-014', heritageNumber: 'HAY-SP3400VSPND', name: 'Hayward EcoStar SVRS', category: 'Pumps', subcategory: 'Variable Speed', price: 1899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-VS-015', heritageNumber: 'PEN-011056', name: 'Pentair IntelliFlo2 VST', category: 'Pumps', subcategory: 'Variable Speed', price: 1599.00, unit: 'EA', manufacturer: 'Pentair' },

  // PUMPS - Single Speed (35 products)
  { sku: 'PUMP-SS-001', heritageNumber: 'HAY-SP2607X10', name: 'Hayward Super Pump 1.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 449.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-SS-002', heritageNumber: 'HAY-SP2610X15', name: 'Hayward Super Pump 1.5HP', category: 'Pumps', subcategory: 'Single Speed', price: 549.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-SS-003', heritageNumber: 'HAY-SP2615X20', name: 'Hayward Super Pump 2.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 649.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-SS-004', heritageNumber: 'PEN-340039', name: 'Pentair WhisperFlo 1.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 499.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-SS-005', heritageNumber: 'PEN-340040', name: 'Pentair WhisperFlo 1.5HP', category: 'Pumps', subcategory: 'Single Speed', price: 599.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-SS-006', heritageNumber: 'PEN-340041', name: 'Pentair WhisperFlo 2.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 699.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-SS-007', heritageNumber: 'JAN-FHPM10', name: 'Jandy FloPro 1.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 425.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'PUMP-SS-008', heritageNumber: 'JAN-FHPM15', name: 'Jandy FloPro 1.5HP', category: 'Pumps', subcategory: 'Single Speed', price: 499.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'PUMP-SS-009', heritageNumber: 'JAN-FHPM20', name: 'Jandy FloPro 2.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 575.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'PUMP-SS-010', heritageNumber: 'HAY-SP2307X10', name: 'Hayward MaxFlo XL 1.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 399.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-SS-011', heritageNumber: 'HAY-SP2310X15', name: 'Hayward MaxFlo XL 1.5HP', category: 'Pumps', subcategory: 'Single Speed', price: 479.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-SS-012', heritageNumber: 'STA-P6E6E-206L', name: 'Sta-Rite Max-E-Pro 1.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 469.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'PUMP-SS-013', heritageNumber: 'STA-P6E6F-207L', name: 'Sta-Rite Max-E-Pro 1.5HP', category: 'Pumps', subcategory: 'Single Speed', price: 549.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'PUMP-SS-014', heritageNumber: 'STA-P6E6G-208L', name: 'Sta-Rite Max-E-Pro 2.0HP', category: 'Pumps', subcategory: 'Single Speed', price: 629.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'PUMP-SS-015', heritageNumber: 'HAY-SP1580X15', name: 'Hayward Power-Flo LX 1.5HP', category: 'Pumps', subcategory: 'Single Speed', price: 299.00, unit: 'EA', manufacturer: 'Hayward' },

  // PUMPS - Commercial (20 products)
  { sku: 'PUMP-CM-001', heritageNumber: 'HAY-SP3025X30', name: 'Hayward TriStar 3.0HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 1099.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-CM-002', heritageNumber: 'HAY-SP3030X50', name: 'Hayward TriStar 5.0HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 1599.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-CM-003', heritageNumber: 'PEN-011513', name: 'Pentair EQ500 5HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 2199.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-CM-004', heritageNumber: 'PEN-011515', name: 'Pentair EQ750 7.5HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 2899.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-CM-005', heritageNumber: 'PEN-011518', name: 'Pentair EQ1000 10HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 3599.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-CM-006', heritageNumber: 'HAY-SP3220C', name: 'Hayward HCP3000 3HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 1299.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-CM-007', heritageNumber: 'HAY-SP3250C', name: 'Hayward HCP5000 5HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 1799.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-CM-008', heritageNumber: 'STA-?"EQ500', name: 'Sta-Rite?"EQ 5HP Commercial', category: 'Pumps', subcategory: 'Commercial', price: 2099.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'PUMP-CM-009', heritageNumber: 'PEN-340074', name: 'Pentair Challenger 2HP High Flow', category: 'Pumps', subcategory: 'Commercial', price: 899.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-CM-010', heritageNumber: 'PEN-340075', name: 'Pentair Challenger 3HP High Flow', category: 'Pumps', subcategory: 'Commercial', price: 1099.00, unit: 'EA', manufacturer: 'Pentair' },

  // PUMPS - Booster (15 products)
  { sku: 'PUMP-BP-001', heritageNumber: 'PEN-LA01N', name: 'Pentair Letro Booster Pump', category: 'Pumps', subcategory: 'Booster', price: 549.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PUMP-BP-002', heritageNumber: 'POL-PB4-60', name: 'Polaris PB4-60 Booster Pump', category: 'Pumps', subcategory: 'Booster', price: 599.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'PUMP-BP-003', heritageNumber: 'HAY-6060', name: 'Hayward 6060 Booster Pump', category: 'Pumps', subcategory: 'Booster', price: 449.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PUMP-BP-004', heritageNumber: 'JAN-PHPB75', name: 'Jandy PlusHP Booster Pump', category: 'Pumps', subcategory: 'Booster', price: 499.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'PUMP-BP-005', heritageNumber: 'POL-PB4-SQ', name: 'Polaris PB4-SQ Quiet Booster', category: 'Pumps', subcategory: 'Booster', price: 649.00, unit: 'EA', manufacturer: 'Polaris' },

  // FILTERS - Cartridge (40 products)
  { sku: 'FILT-CF-001', heritageNumber: 'HAY-C17502', name: 'Hayward SwimClear C175S 175sqft', category: 'Filters', subcategory: 'Cartridge', price: 899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-CF-002', heritageNumber: 'HAY-C32002', name: 'Hayward SwimClear C3030 300sqft', category: 'Filters', subcategory: 'Cartridge', price: 1299.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-CF-003', heritageNumber: 'HAY-C48002', name: 'Hayward SwimClear C4030 425sqft', category: 'Filters', subcategory: 'Cartridge', price: 1599.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-CF-004', heritageNumber: 'HAY-C75002', name: 'Hayward SwimClear C5030 525sqft', category: 'Filters', subcategory: 'Cartridge', price: 1899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-CF-005', heritageNumber: 'PEN-160340', name: 'Pentair Clean & Clear 150sqft', category: 'Filters', subcategory: 'Cartridge', price: 749.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-CF-006', heritageNumber: 'PEN-160341', name: 'Pentair Clean & Clear 200sqft', category: 'Filters', subcategory: 'Cartridge', price: 899.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-CF-007', heritageNumber: 'PEN-160342', name: 'Pentair Clean & Clear Plus 320sqft', category: 'Filters', subcategory: 'Cartridge', price: 1149.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-CF-008', heritageNumber: 'PEN-160343', name: 'Pentair Clean & Clear Plus 420sqft', category: 'Filters', subcategory: 'Cartridge', price: 1449.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-CF-009', heritageNumber: 'PEN-160344', name: 'Pentair Clean & Clear Plus 520sqft', category: 'Filters', subcategory: 'Cartridge', price: 1749.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-CF-010', heritageNumber: 'JAN-CL340', name: 'Jandy CL340 Cartridge Filter', category: 'Filters', subcategory: 'Cartridge', price: 849.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'FILT-CF-011', heritageNumber: 'JAN-CL460', name: 'Jandy CL460 Cartridge Filter', category: 'Filters', subcategory: 'Cartridge', price: 1049.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'FILT-CF-012', heritageNumber: 'JAN-CL580', name: 'Jandy CL580 Cartridge Filter', category: 'Filters', subcategory: 'Cartridge', price: 1349.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'FILT-CF-013', heritageNumber: 'STA-25220-0150S', name: 'Sta-Rite System 3 150sqft', category: 'Filters', subcategory: 'Cartridge', price: 799.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'FILT-CF-014', heritageNumber: 'STA-25220-0300S', name: 'Sta-Rite System 3 300sqft', category: 'Filters', subcategory: 'Cartridge', price: 1199.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'FILT-CF-015', heritageNumber: 'STA-25220-0450S', name: 'Sta-Rite System 3 450sqft', category: 'Filters', subcategory: 'Cartridge', price: 1499.00, unit: 'EA', manufacturer: 'Sta-Rite' },

  // FILTERS - DE (25 products)
  { sku: 'FILT-DE-001', heritageNumber: 'HAY-DE4820', name: 'Hayward Pro-Grid DE 48sqft', category: 'Filters', subcategory: 'DE', price: 1249.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-DE-002', heritageNumber: 'HAY-DE6020', name: 'Hayward Pro-Grid DE 60sqft', category: 'Filters', subcategory: 'DE', price: 1399.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-DE-003', heritageNumber: 'HAY-DE7220', name: 'Hayward Pro-Grid DE 72sqft', category: 'Filters', subcategory: 'DE', price: 1549.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-DE-004', heritageNumber: 'PEN-180007', name: 'Pentair FNS Plus 36sqft DE', category: 'Filters', subcategory: 'DE', price: 1099.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-DE-005', heritageNumber: 'PEN-180008', name: 'Pentair FNS Plus 48sqft DE', category: 'Filters', subcategory: 'DE', price: 1249.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-DE-006', heritageNumber: 'PEN-180009', name: 'Pentair FNS Plus 60sqft DE', category: 'Filters', subcategory: 'DE', price: 1399.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-DE-007', heritageNumber: 'JAN-DEV48', name: 'Jandy DEV48 48sqft DE Filter', category: 'Filters', subcategory: 'DE', price: 1199.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'FILT-DE-008', heritageNumber: 'JAN-DEV60', name: 'Jandy DEV60 60sqft DE Filter', category: 'Filters', subcategory: 'DE', price: 1349.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'FILT-DE-009', heritageNumber: 'STA-25054-000S', name: 'Sta-Rite System 3 DE 36sqft', category: 'Filters', subcategory: 'DE', price: 1149.00, unit: 'EA', manufacturer: 'Sta-Rite' },
  { sku: 'FILT-DE-010', heritageNumber: 'STA-25056-000S', name: 'Sta-Rite System 3 DE 48sqft', category: 'Filters', subcategory: 'DE', price: 1299.00, unit: 'EA', manufacturer: 'Sta-Rite' },

  // FILTERS - Sand (20 products)
  { sku: 'FILT-SD-001', heritageNumber: 'HAY-S220T2', name: 'Hayward Pro Series 22" Sand Filter', category: 'Filters', subcategory: 'Sand', price: 649.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-SD-002', heritageNumber: 'HAY-S244T2', name: 'Hayward Pro Series 24" Sand Filter', category: 'Filters', subcategory: 'Sand', price: 749.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-SD-003', heritageNumber: 'HAY-S270T2', name: 'Hayward Pro Series 27" Sand Filter', category: 'Filters', subcategory: 'Sand', price: 899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-SD-004', heritageNumber: 'HAY-S310T2', name: 'Hayward Pro Series 31" Sand Filter', category: 'Filters', subcategory: 'Sand', price: 1099.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'FILT-SD-005', heritageNumber: 'PEN-145360', name: 'Pentair Sand Dollar 19" Sand', category: 'Filters', subcategory: 'Sand', price: 449.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-SD-006', heritageNumber: 'PEN-145361', name: 'Pentair Sand Dollar 22" Sand', category: 'Filters', subcategory: 'Sand', price: 549.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-SD-007', heritageNumber: 'PEN-145362', name: 'Pentair Sand Dollar 26" Sand', category: 'Filters', subcategory: 'Sand', price: 699.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'FILT-SD-008', heritageNumber: 'JAN-JS60', name: 'Jandy JS Series 60 Sand Filter', category: 'Filters', subcategory: 'Sand', price: 749.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'FILT-SD-009', heritageNumber: 'JAN-JS100', name: 'Jandy JS Series 100 Sand Filter', category: 'Filters', subcategory: 'Sand', price: 999.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'FILT-SD-010', heritageNumber: 'STA-143000T', name: 'Sta-Rite Posi-Clear 36" Sand', category: 'Filters', subcategory: 'Sand', price: 1299.00, unit: 'EA', manufacturer: 'Sta-Rite' },

  // FILTER CARTRIDGES - Replacement (50 products)
  { sku: 'CART-001', heritageNumber: 'HAY-CX1750RE', name: 'Hayward SwimClear C175S Cartridge', category: 'Filters', subcategory: 'Replacement Cartridges', price: 149.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CART-002', heritageNumber: 'HAY-CX870XRE', name: 'Hayward C900 Cartridge', category: 'Filters', subcategory: 'Replacement Cartridges', price: 89.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CART-003', heritageNumber: 'HAY-CX1200RE', name: 'Hayward C1200 Cartridge', category: 'Filters', subcategory: 'Replacement Cartridges', price: 119.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CART-004', heritageNumber: 'PEN-178580', name: 'Pentair Clean & Clear 100sqft Cart', category: 'Filters', subcategory: 'Replacement Cartridges', price: 79.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CART-005', heritageNumber: 'PEN-178584', name: 'Pentair Clean & Clear 150sqft Cart', category: 'Filters', subcategory: 'Replacement Cartridges', price: 99.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CART-006', heritageNumber: 'PEN-178585', name: 'Pentair Clean & Clear 200sqft Cart', category: 'Filters', subcategory: 'Replacement Cartridges', price: 129.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CART-007', heritageNumber: 'PEN-R173215', name: 'Pentair CC100 Replacement Cart', category: 'Filters', subcategory: 'Replacement Cartridges', price: 74.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CART-008', heritageNumber: 'JAN-R0462200', name: 'Jandy CL340 Replacement Cartridge', category: 'Filters', subcategory: 'Replacement Cartridges', price: 109.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'CART-009', heritageNumber: 'JAN-R0462300', name: 'Jandy CL460 Replacement Cartridge', category: 'Filters', subcategory: 'Replacement Cartridges', price: 139.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'CART-010', heritageNumber: 'UNI-C7470', name: 'Unicel C-7470 Universal Cartridge', category: 'Filters', subcategory: 'Replacement Cartridges', price: 69.00, unit: 'EA', manufacturer: 'Unicel' },
  { sku: 'CART-011', heritageNumber: 'UNI-C7483', name: 'Unicel C-7483 Hayward Compatible', category: 'Filters', subcategory: 'Replacement Cartridges', price: 79.00, unit: 'EA', manufacturer: 'Unicel' },
  { sku: 'CART-012', heritageNumber: 'UNI-C7472', name: 'Unicel C-7472 Pentair Compatible', category: 'Filters', subcategory: 'Replacement Cartridges', price: 74.00, unit: 'EA', manufacturer: 'Unicel' },
  { sku: 'CART-013', heritageNumber: 'FIL-FC3748', name: 'Filbur FC-3748 Replacement', category: 'Filters', subcategory: 'Replacement Cartridges', price: 59.00, unit: 'EA', manufacturer: 'Filbur' },
  { sku: 'CART-014', heritageNumber: 'FIL-FC3751', name: 'Filbur FC-3751 Replacement', category: 'Filters', subcategory: 'Replacement Cartridges', price: 64.00, unit: 'EA', manufacturer: 'Filbur' },
  { sku: 'CART-015', heritageNumber: 'PLE-PA100N', name: 'Pleatco PA100N Hayward Compatible', category: 'Filters', subcategory: 'Replacement Cartridges', price: 89.00, unit: 'EA', manufacturer: 'Pleatco' },

  // HEATERS - Gas (40 products)
  { sku: 'HEAT-GS-001', heritageNumber: 'HAY-H150FDN', name: 'Hayward H150FD 150K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2499.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-002', heritageNumber: 'HAY-H200FDN', name: 'Hayward H200FD 200K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2799.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-003', heritageNumber: 'HAY-H250FDN', name: 'Hayward H250FD 250K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2999.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-004', heritageNumber: 'HAY-H300FDN', name: 'Hayward H300FD 300K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 3199.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-005', heritageNumber: 'HAY-H350FDN', name: 'Hayward H350FD 350K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 3399.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-006', heritageNumber: 'HAY-H400FDN', name: 'Hayward H400FD 400K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 3599.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-007', heritageNumber: 'HAY-H150FDP', name: 'Hayward H150FD 150K BTU Propane', category: 'Heaters', subcategory: 'Gas', price: 2499.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-008', heritageNumber: 'HAY-H400FDP', name: 'Hayward H400FD 400K BTU Propane', category: 'Heaters', subcategory: 'Gas', price: 3599.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-GS-009', heritageNumber: 'PEN-460732', name: 'Pentair MasterTemp 200 Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2649.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-GS-010', heritageNumber: 'PEN-460733', name: 'Pentair MasterTemp 250 Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2899.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-GS-011', heritageNumber: 'PEN-460734', name: 'Pentair MasterTemp 300 Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 3149.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-GS-012', heritageNumber: 'PEN-460735', name: 'Pentair MasterTemp 400 Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 3499.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-GS-013', heritageNumber: 'PEN-460736', name: 'Pentair MasterTemp 400 Propane', category: 'Heaters', subcategory: 'Gas', price: 3499.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-GS-014', heritageNumber: 'RAY-206A', name: 'Raypak 206A 199K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2399.00, unit: 'EA', manufacturer: 'Raypak' },
  { sku: 'HEAT-GS-015', heritageNumber: 'RAY-266A', name: 'Raypak 266A 266K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2699.00, unit: 'EA', manufacturer: 'Raypak' },
  { sku: 'HEAT-GS-016', heritageNumber: 'RAY-336A', name: 'Raypak 336A 336K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2999.00, unit: 'EA', manufacturer: 'Raypak' },
  { sku: 'HEAT-GS-017', heritageNumber: 'RAY-406A', name: 'Raypak 406A 399K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 3299.00, unit: 'EA', manufacturer: 'Raypak' },
  { sku: 'HEAT-GS-018', heritageNumber: 'JAN-JXI200N', name: 'Jandy JXi 200K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2749.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'HEAT-GS-019', heritageNumber: 'JAN-JXI260N', name: 'Jandy JXi 260K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 2999.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'HEAT-GS-020', heritageNumber: 'JAN-JXI400N', name: 'Jandy JXi 400K BTU Natural Gas', category: 'Heaters', subcategory: 'Gas', price: 3599.00, unit: 'EA', manufacturer: 'Jandy' },

  // HEATERS - Heat Pumps (25 products)
  { sku: 'HEAT-HP-001', heritageNumber: 'HAY-HP50HA2', name: 'Hayward HeatPro 50K BTU Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 3299.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-HP-002', heritageNumber: 'HAY-HP70HA2', name: 'Hayward HeatPro 70K BTU Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 3699.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-HP-003', heritageNumber: 'HAY-HP95HA2', name: 'Hayward HeatPro 95K BTU Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 4199.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-HP-004', heritageNumber: 'HAY-HP125HA2', name: 'Hayward HeatPro 125K BTU Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 4699.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-HP-005', heritageNumber: 'HAY-HP140HA2', name: 'Hayward HeatPro 140K BTU Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 5199.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-HP-006', heritageNumber: 'PEN-460961', name: 'Pentair UltraTemp 70 Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 3899.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-HP-007', heritageNumber: 'PEN-460962', name: 'Pentair UltraTemp 90 Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 4299.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-HP-008', heritageNumber: 'PEN-460963', name: 'Pentair UltraTemp 110 Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 4799.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-HP-009', heritageNumber: 'PEN-460964', name: 'Pentair UltraTemp 140 Heat Pump', category: 'Heaters', subcategory: 'Heat Pump', price: 5399.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-HP-010', heritageNumber: 'JAN-JE2500T', name: 'Jandy JE2500T Heat Pump 88K BTU', category: 'Heaters', subcategory: 'Heat Pump', price: 3999.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'HEAT-HP-011', heritageNumber: 'JAN-JE3000T', name: 'Jandy JE3000T Heat Pump 109K BTU', category: 'Heaters', subcategory: 'Heat Pump', price: 4499.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'HEAT-HP-012', heritageNumber: 'AQU-HPC125', name: 'AquaCal HeatWave 125K BTU', category: 'Heaters', subcategory: 'Heat Pump', price: 4899.00, unit: 'EA', manufacturer: 'AquaCal' },
  { sku: 'HEAT-HP-013', heritageNumber: 'AQU-TRO125', name: 'AquaCal TropiCal 125K BTU', category: 'Heaters', subcategory: 'Heat Pump', price: 5299.00, unit: 'EA', manufacturer: 'AquaCal' },

  // HEATERS - Electric (10 products)
  { sku: 'HEAT-EL-001', heritageNumber: 'HAY-CSPAXI55', name: 'Hayward CSPAXI 5.5kW Electric Heater', category: 'Heaters', subcategory: 'Electric', price: 899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-EL-002', heritageNumber: 'HAY-CSPAXI11', name: 'Hayward CSPAXI 11kW Electric Heater', category: 'Heaters', subcategory: 'Electric', price: 1099.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'HEAT-EL-003', heritageNumber: 'PEN-460034', name: 'Pentair ETi 400 Electric Heater', category: 'Heaters', subcategory: 'Electric', price: 1499.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'HEAT-EL-004', heritageNumber: 'RAY-E3T', name: 'Raypak E3T 27kW Electric Heater', category: 'Heaters', subcategory: 'Electric', price: 1799.00, unit: 'EA', manufacturer: 'Raypak' },
  { sku: 'HEAT-EL-005', heritageNumber: 'RAY-E3T-36', name: 'Raypak E3T 36kW Electric Heater', category: 'Heaters', subcategory: 'Electric', price: 2199.00, unit: 'EA', manufacturer: 'Raypak' },

  // HEATERS - Tube Bundles (9 products)
  { sku: 'HEAT-TB-001', heritageNumber: '014653F', name: 'Round Tube Bundle Raypak X-Therm', category: 'Heaters', subcategory: 'Tube Bundles', price: 28254.44, unit: 'EA', manufacturer: 'Raypak', description: 'Replacement tube bundle for Raypak X-Therm commercial heaters' },
  { sku: 'HEAT-TB-002', heritageNumber: '010055F', name: 'Tube Bundle 207A Raypak', category: 'Heaters', subcategory: 'Tube Bundles', price: 1542.44, unit: 'EA', manufacturer: 'Raypak', description: 'Replacement tube bundle for Raypak 207A heaters' },
  { sku: 'HEAT-TB-003', heritageNumber: '010061F', name: 'Tube Bundle 337A Raypak', category: 'Heaters', subcategory: 'Tube Bundles', price: 1439.20, unit: 'EA', manufacturer: 'Raypak', description: 'Replacement tube bundle for Raypak 337A heaters' },
  { sku: 'HEAT-TB-004', heritageNumber: 'RAY006735F', name: 'Tube Bundle 405A Raypak', category: 'Heaters', subcategory: 'Tube Bundles', price: 1805.91, unit: 'EA', manufacturer: 'Raypak', description: 'Replacement tube bundle for Raypak 405A heaters' },
  { sku: 'HEAT-TB-005', heritageNumber: '010058F', name: 'Tube Bundle 407A Old Style Raypak Before 12/2009', category: 'Heaters', subcategory: 'Tube Bundles', price: 1813.42, unit: 'EA', manufacturer: 'Raypak', description: 'Replacement tube bundle for Raypak 407A heaters manufactured before December 2009' },
  { sku: 'HEAT-TB-006', heritageNumber: 'JNDR0589500', name: 'Tube Bundle Gasket & Seal Kit Jandy', category: 'Heaters', subcategory: 'Tube Bundles', price: 120.04, unit: 'EA', manufacturer: 'Jandy', description: 'Gasket and seal kit for Jandy tube bundle installation' },
  { sku: 'HEAT-TB-007', heritageNumber: '800014B', name: 'Tube Bundle Gasket Kit Raypak', category: 'Heaters', subcategory: 'Tube Bundles', price: 40.19, unit: 'EA', manufacturer: 'Raypak', description: 'Gasket kit for Raypak tube bundle installation' },
  { sku: 'HEAT-TB-008', heritageNumber: 'R0589405', name: 'Tube Bundle Jandy JXI', category: 'Heaters', subcategory: 'Tube Bundles', price: 1737.21, unit: 'EA', manufacturer: 'Jandy', description: 'Replacement tube bundle for Jandy JXI heaters' },
  { sku: 'HEAT-TB-009', heritageNumber: '017977F', name: 'Tube Bundle Only 407A New Style After 12/2009', category: 'Heaters', subcategory: 'Tube Bundles', price: 2047.88, unit: 'EA', manufacturer: 'Raypak', description: 'Replacement tube bundle for Raypak 407A heaters manufactured after December 2009' },

  // AUTOMATION - Controllers (40 products)
  { sku: 'AUTO-CT-001', heritageNumber: 'HAY-AQL-PS4', name: 'Hayward OmniLogic Pool Control', category: 'Automation', subcategory: 'Controllers', price: 2499.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CT-002', heritageNumber: 'HAY-AQL-PS8', name: 'Hayward OmniLogic w/8 Relays', category: 'Automation', subcategory: 'Controllers', price: 2999.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CT-003', heritageNumber: 'HAY-AQL-PS16', name: 'Hayward OmniLogic w/16 Relays', category: 'Automation', subcategory: 'Controllers', price: 3499.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CT-004', heritageNumber: 'HAY-PL-PS4', name: 'Hayward ProLogic 4 Relay System', category: 'Automation', subcategory: 'Controllers', price: 1299.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CT-005', heritageNumber: 'HAY-PL-PS8', name: 'Hayward ProLogic 8 Relay System', category: 'Automation', subcategory: 'Controllers', price: 1699.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CT-006', heritageNumber: 'PEN-521179', name: 'Pentair IntelliCenter i5PS', category: 'Automation', subcategory: 'Controllers', price: 2299.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'AUTO-CT-007', heritageNumber: 'PEN-521181', name: 'Pentair IntelliCenter i8PS', category: 'Automation', subcategory: 'Controllers', price: 2699.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'AUTO-CT-008', heritageNumber: 'PEN-521182', name: 'Pentair IntelliCenter i10PS', category: 'Automation', subcategory: 'Controllers', price: 3199.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'AUTO-CT-009', heritageNumber: 'PEN-520136', name: 'Pentair EasyTouch 4PSC', category: 'Automation', subcategory: 'Controllers', price: 1599.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'AUTO-CT-010', heritageNumber: 'PEN-520137', name: 'Pentair EasyTouch 8PSC', category: 'Automation', subcategory: 'Controllers', price: 1899.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'AUTO-CT-011', heritageNumber: 'JAN-iQPUMP01', name: 'Jandy iAquaLink 2.0 System', category: 'Automation', subcategory: 'Controllers', price: 2199.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'AUTO-CT-012', heritageNumber: 'JAN-AQRS4', name: 'Jandy AquaLink RS4 One Touch', category: 'Automation', subcategory: 'Controllers', price: 1499.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'AUTO-CT-013', heritageNumber: 'JAN-AQRS8', name: 'Jandy AquaLink RS8 One Touch', category: 'Automation', subcategory: 'Controllers', price: 1899.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'AUTO-CT-014', heritageNumber: 'JAN-AQRS16', name: 'Jandy AquaLink RS16 Pool & Spa', category: 'Automation', subcategory: 'Controllers', price: 2399.00, unit: 'EA', manufacturer: 'Jandy' },

  // AUTOMATION - Chemical Controllers (25 products)
  { sku: 'AUTO-CH-001', heritageNumber: 'HAY-CAT2000', name: 'Hayward CAT 2000 Controller', category: 'Automation', subcategory: 'Chemical Controllers', price: 1899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CH-002', heritageNumber: 'HAY-CAT4000', name: 'Hayward CAT 4000 Controller', category: 'Automation', subcategory: 'Chemical Controllers', price: 2499.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CH-003', heritageNumber: 'PEN-521356', name: 'Pentair IntelliChem Controller', category: 'Automation', subcategory: 'Chemical Controllers', price: 2199.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'AUTO-CH-004', heritageNumber: 'HAY-HLCHEM', name: 'Hayward Sense & Dispense Chem', category: 'Automation', subcategory: 'Chemical Controllers', price: 1799.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'AUTO-CH-005', heritageNumber: 'STE-WEBCONNECT', name: 'Stenner WebConnect Controller', category: 'Automation', subcategory: 'Chemical Controllers', price: 1599.00, unit: 'EA', manufacturer: 'Stenner' },
  { sku: 'AUTO-CH-006', heritageNumber: 'HAL-LCA', name: 'Halo LCA Commercial Controller', category: 'Automation', subcategory: 'Chemical Controllers', price: 3299.00, unit: 'EA', manufacturer: 'Halo' },
  { sku: 'AUTO-CH-007', heritageNumber: 'PRO-CLEAR', name: 'ProMinent Clear Controller', category: 'Automation', subcategory: 'Chemical Controllers', price: 2899.00, unit: 'EA', manufacturer: 'ProMinent' },
  { sku: 'AUTO-CH-008', heritageNumber: 'PEN-523317', name: 'Pentair IntelliConnect Controller', category: 'Automation', subcategory: 'Chemical Controllers', price: 649.00, unit: 'EA', manufacturer: 'Pentair' },

  // SALT SYSTEMS (30 products)
  { sku: 'SALT-001', heritageNumber: 'HAY-T-CELL-15', name: 'Hayward TurboCell T-Cell-15 40K', category: 'Automation', subcategory: 'Salt Systems', price: 899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'SALT-002', heritageNumber: 'HAY-T-CELL-9', name: 'Hayward TurboCell T-Cell-9 25K', category: 'Automation', subcategory: 'Salt Systems', price: 749.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'SALT-003', heritageNumber: 'HAY-T-CELL-3', name: 'Hayward TurboCell T-Cell-3 15K', category: 'Automation', subcategory: 'Salt Systems', price: 599.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'SALT-004', heritageNumber: 'HAY-AQR15', name: 'Hayward AquaRite 940 Salt System', category: 'Automation', subcategory: 'Salt Systems', price: 1299.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'SALT-005', heritageNumber: 'HAY-AQR25', name: 'Hayward AquaRite 925 Salt System', category: 'Automation', subcategory: 'Salt Systems', price: 1499.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'SALT-006', heritageNumber: 'HAY-AQR40', name: 'Hayward AquaRite 900 Salt System', category: 'Automation', subcategory: 'Salt Systems', price: 1699.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'SALT-007', heritageNumber: 'PEN-520555', name: 'Pentair IntelliChlor IC20 20K', category: 'Automation', subcategory: 'Salt Systems', price: 799.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'SALT-008', heritageNumber: 'PEN-520554', name: 'Pentair IntelliChlor IC40 40K', category: 'Automation', subcategory: 'Salt Systems', price: 999.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'SALT-009', heritageNumber: 'PEN-520556', name: 'Pentair IntelliChlor IC60 60K', category: 'Automation', subcategory: 'Salt Systems', price: 1199.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'SALT-010', heritageNumber: 'JAN-APURE1400', name: 'Jandy AquaPure Ei 35K Cell', category: 'Automation', subcategory: 'Salt Systems', price: 649.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'SALT-011', heritageNumber: 'JAN-APURE2400', name: 'Jandy AquaPure 1400 System', category: 'Automation', subcategory: 'Salt Systems', price: 1399.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'SALT-012', heritageNumber: 'CIR-520670', name: 'CircuPool CORE35 Salt System', category: 'Automation', subcategory: 'Salt Systems', price: 699.00, unit: 'EA', manufacturer: 'CircuPool' },
  { sku: 'SALT-013', heritageNumber: 'CIR-520671', name: 'CircuPool CORE55 Salt System', category: 'Automation', subcategory: 'Salt Systems', price: 899.00, unit: 'EA', manufacturer: 'CircuPool' },

  // VALVES (60 products)
  { sku: 'VALV-001', heritageNumber: 'JAN-4715', name: 'Jandy 2-Way Valve 1.5" Gray', category: 'Valves', subcategory: '2-Way', price: 49.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-002', heritageNumber: 'JAN-4717', name: 'Jandy 2-Way Valve 2" Gray', category: 'Valves', subcategory: '2-Way', price: 59.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-003', heritageNumber: 'JAN-4719', name: 'Jandy 2-Way Valve 2.5" Gray', category: 'Valves', subcategory: '2-Way', price: 79.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-004', heritageNumber: 'JAN-4724', name: 'Jandy 3-Way Valve 1.5" Gray', category: 'Valves', subcategory: '3-Way', price: 69.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-005', heritageNumber: 'JAN-4727', name: 'Jandy 3-Way Valve 2" Gray', category: 'Valves', subcategory: '3-Way', price: 89.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-006', heritageNumber: 'JAN-4729', name: 'Jandy 3-Way Valve 2.5" Gray', category: 'Valves', subcategory: '3-Way', price: 119.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-007', heritageNumber: 'HAY-SP0710X62', name: 'Hayward 2-Way Valve 1.5" CPVC', category: 'Valves', subcategory: '2-Way', price: 44.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'VALV-008', heritageNumber: 'HAY-SP0720X62', name: 'Hayward 2-Way Valve 2" CPVC', category: 'Valves', subcategory: '2-Way', price: 54.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'VALV-009', heritageNumber: 'HAY-SP0735X62', name: 'Hayward 3-Way Valve 1.5" CPVC', category: 'Valves', subcategory: '3-Way', price: 64.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'VALV-010', heritageNumber: 'HAY-SP0740X62', name: 'Hayward 3-Way Valve 2" CPVC', category: 'Valves', subcategory: '3-Way', price: 79.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'VALV-011', heritageNumber: 'PEN-263037', name: 'Pentair 2-Way Valve 1.5" PVC', category: 'Valves', subcategory: '2-Way', price: 42.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-012', heritageNumber: 'PEN-263038', name: 'Pentair 2-Way Valve 2" PVC', category: 'Valves', subcategory: '2-Way', price: 52.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-013', heritageNumber: 'PEN-263064', name: 'Pentair 3-Way Valve 1.5" PVC', category: 'Valves', subcategory: '3-Way', price: 62.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-014', heritageNumber: 'PEN-263065', name: 'Pentair 3-Way Valve 2" PVC', category: 'Valves', subcategory: '3-Way', price: 74.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-015', heritageNumber: 'JAN-7305', name: 'Jandy NeverLube 2-Way 2" Valve', category: 'Valves', subcategory: '2-Way', price: 99.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-016', heritageNumber: 'JAN-7306', name: 'Jandy NeverLube 3-Way 2" Valve', category: 'Valves', subcategory: '3-Way', price: 129.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-017', heritageNumber: 'PEN-263081', name: 'Pentair Check Valve 1.5" Swing', category: 'Valves', subcategory: 'Check', price: 29.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-018', heritageNumber: 'PEN-263082', name: 'Pentair Check Valve 2" Swing', category: 'Valves', subcategory: 'Check', price: 39.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-019', heritageNumber: 'HAY-SP1480', name: 'Hayward Spring Check Valve 1.5"', category: 'Valves', subcategory: 'Check', price: 34.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'VALV-020', heritageNumber: 'HAY-SP1490', name: 'Hayward Spring Check Valve 2"', category: 'Valves', subcategory: 'Check', price: 44.00, unit: 'EA', manufacturer: 'Hayward' },

  // VALVE ACTUATORS (20 products)
  { sku: 'VALV-ACT-001', heritageNumber: 'JAN-4424', name: 'Jandy Valve Actuator 180deg', category: 'Valves', subcategory: 'Actuators', price: 299.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-ACT-002', heritageNumber: 'JAN-4424R', name: 'Jandy Valve Actuator 24V 180deg', category: 'Valves', subcategory: 'Actuators', price: 329.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'VALV-ACT-003', heritageNumber: 'PEN-263045', name: 'Pentair CVA-24 Valve Actuator', category: 'Valves', subcategory: 'Actuators', price: 279.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-ACT-004', heritageNumber: 'PEN-263046', name: 'Pentair CVA-24T Valve Actuator', category: 'Valves', subcategory: 'Actuators', price: 309.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'VALV-ACT-005', heritageNumber: 'HAY-GVA24', name: 'Hayward GoldLine Valve Actuator', category: 'Valves', subcategory: 'Actuators', price: 269.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'VALV-ACT-006', heritageNumber: 'HAY-GVA24P', name: 'Hayward GoldLine Actuator w/Power', category: 'Valves', subcategory: 'Actuators', price: 299.00, unit: 'EA', manufacturer: 'Hayward' },

  // CHEMICALS - Chlorine (40 products)
  { sku: 'CHEM-CL-001', heritageNumber: 'BIO-22201', name: 'BioGuard Chlorine Tabs 3" 25lb', category: 'Chemicals', subcategory: 'Chlorine', price: 149.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-CL-002', heritageNumber: 'BIO-22202', name: 'BioGuard Chlorine Tabs 3" 50lb', category: 'Chemicals', subcategory: 'Chlorine', price: 279.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-CL-003', heritageNumber: 'BIO-22210', name: 'BioGuard Chlorine Sticks 5lb', category: 'Chemicals', subcategory: 'Chlorine', price: 39.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-CL-004', heritageNumber: 'BIO-22205', name: 'BioGuard Cal-Hypo Shock 1lb', category: 'Chemicals', subcategory: 'Chlorine', price: 8.99, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-CL-005', heritageNumber: 'BIO-22206', name: 'BioGuard Cal-Hypo Shock 12x1lb', category: 'Chemicals', subcategory: 'Chlorine', price: 89.00, unit: 'CS', manufacturer: 'BioGuard' },
  { sku: 'CHEM-CL-006', heritageNumber: 'HAY-CL210', name: 'Hayward Chlorine Tabs 3" 10lb', category: 'Chemicals', subcategory: 'Chlorine', price: 69.00, unit: 'BK', manufacturer: 'Hayward' },
  { sku: 'CHEM-CL-007', heritageNumber: 'HAY-CL225', name: 'Hayward Chlorine Tabs 3" 25lb', category: 'Chemicals', subcategory: 'Chlorine', price: 159.00, unit: 'BK', manufacturer: 'Hayward' },
  { sku: 'CHEM-CL-008', heritageNumber: 'HAY-CL250', name: 'Hayward Chlorine Tabs 3" 50lb', category: 'Chemicals', subcategory: 'Chlorine', price: 289.00, unit: 'BK', manufacturer: 'Hayward' },
  { sku: 'CHEM-CL-009', heritageNumber: 'PPG-42021', name: 'PPG Cal-Hypo Granular 25lb', category: 'Chemicals', subcategory: 'Chlorine', price: 129.00, unit: 'BK', manufacturer: 'PPG' },
  { sku: 'CHEM-CL-010', heritageNumber: 'PPG-42022', name: 'PPG Cal-Hypo Granular 50lb', category: 'Chemicals', subcategory: 'Chlorine', price: 239.00, unit: 'BK', manufacturer: 'PPG' },
  { sku: 'CHEM-CL-011', heritageNumber: 'PPG-42041', name: 'PPG Dichlor Granular 25lb', category: 'Chemicals', subcategory: 'Chlorine', price: 199.00, unit: 'BK', manufacturer: 'PPG' },
  { sku: 'CHEM-CL-012', heritageNumber: 'PPG-42042', name: 'PPG Dichlor Granular 50lb', category: 'Chemicals', subcategory: 'Chlorine', price: 379.00, unit: 'BK', manufacturer: 'PPG' },
  { sku: 'CHEM-CL-013', heritageNumber: 'ORC-42051', name: 'Oreq Liquid Chlorine 12.5% 4gal', category: 'Chemicals', subcategory: 'Chlorine', price: 24.00, unit: 'CS', manufacturer: 'Oreq' },
  { sku: 'CHEM-CL-014', heritageNumber: 'ORC-42052', name: 'Oreq Liquid Chlorine 12.5% 15gal', category: 'Chemicals', subcategory: 'Chlorine', price: 89.00, unit: 'DR', manufacturer: 'Oreq' },
  { sku: 'CHEM-CL-015', heritageNumber: 'ORC-42053', name: 'Oreq Liquid Chlorine 12.5% 55gal', category: 'Chemicals', subcategory: 'Chlorine', price: 299.00, unit: 'DR', manufacturer: 'Oreq' },

  // CHEMICALS - pH Balance (30 products)
  { sku: 'CHEM-PH-001', heritageNumber: 'BIO-23301', name: 'BioGuard pH Decreaser 6lb', category: 'Chemicals', subcategory: 'pH Balance', price: 19.99, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-PH-002', heritageNumber: 'BIO-23302', name: 'BioGuard pH Decreaser 25lb', category: 'Chemicals', subcategory: 'pH Balance', price: 69.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-PH-003', heritageNumber: 'BIO-23303', name: 'BioGuard pH Decreaser 50lb', category: 'Chemicals', subcategory: 'pH Balance', price: 119.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-PH-004', heritageNumber: 'BIO-23311', name: 'BioGuard pH Increaser 5lb', category: 'Chemicals', subcategory: 'pH Balance', price: 17.99, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-PH-005', heritageNumber: 'BIO-23312', name: 'BioGuard pH Increaser 25lb', category: 'Chemicals', subcategory: 'pH Balance', price: 59.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-PH-006', heritageNumber: 'BIO-23321', name: 'BioGuard Alkalinity Increaser 5lb', category: 'Chemicals', subcategory: 'pH Balance', price: 24.99, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-PH-007', heritageNumber: 'BIO-23322', name: 'BioGuard Alkalinity Increaser 25lb', category: 'Chemicals', subcategory: 'pH Balance', price: 89.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-PH-008', heritageNumber: 'PPG-42301', name: 'PPG Muriatic Acid 2gal', category: 'Chemicals', subcategory: 'pH Balance', price: 15.99, unit: 'CS', manufacturer: 'PPG' },
  { sku: 'CHEM-PH-009', heritageNumber: 'PPG-42302', name: 'PPG Muriatic Acid 4x1gal', category: 'Chemicals', subcategory: 'pH Balance', price: 29.00, unit: 'CS', manufacturer: 'PPG' },
  { sku: 'CHEM-PH-010', heritageNumber: 'PPG-42305', name: 'PPG Soda Ash 25lb', category: 'Chemicals', subcategory: 'pH Balance', price: 49.00, unit: 'BK', manufacturer: 'PPG' },
  { sku: 'CHEM-PH-011', heritageNumber: 'PPG-42306', name: 'PPG Soda Ash 50lb', category: 'Chemicals', subcategory: 'pH Balance', price: 89.00, unit: 'BK', manufacturer: 'PPG' },
  { sku: 'CHEM-PH-012', heritageNumber: 'PPG-42310', name: 'PPG Sodium Bicarb 25lb', category: 'Chemicals', subcategory: 'pH Balance', price: 39.00, unit: 'BK', manufacturer: 'PPG' },
  { sku: 'CHEM-PH-013', heritageNumber: 'PPG-42311', name: 'PPG Sodium Bicarb 50lb', category: 'Chemicals', subcategory: 'pH Balance', price: 69.00, unit: 'BK', manufacturer: 'PPG' },

  // CHEMICALS - Specialty (40 products)
  { sku: 'CHEM-SP-001', heritageNumber: 'BIO-24401', name: 'BioGuard Algae Guard 1qt', category: 'Chemicals', subcategory: 'Specialty', price: 24.99, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-002', heritageNumber: 'BIO-24402', name: 'BioGuard Algae Guard 1gal', category: 'Chemicals', subcategory: 'Specialty', price: 79.00, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-003', heritageNumber: 'BIO-24410', name: 'BioGuard Pool Complete 1qt', category: 'Chemicals', subcategory: 'Specialty', price: 34.99, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-004', heritageNumber: 'BIO-24411', name: 'BioGuard Pool Complete 1gal', category: 'Chemicals', subcategory: 'Specialty', price: 99.00, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-005', heritageNumber: 'BIO-24421', name: 'BioGuard Stabilizer 100 4lb', category: 'Chemicals', subcategory: 'Specialty', price: 39.99, unit: 'EA', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-006', heritageNumber: 'BIO-24422', name: 'BioGuard Stabilizer 100 25lb', category: 'Chemicals', subcategory: 'Specialty', price: 169.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-007', heritageNumber: 'BIO-24423', name: 'BioGuard Stabilizer 100 50lb', category: 'Chemicals', subcategory: 'Specialty', price: 299.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-008', heritageNumber: 'BIO-24431', name: 'BioGuard Calcium Hardness 12lb', category: 'Chemicals', subcategory: 'Specialty', price: 49.99, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-009', heritageNumber: 'BIO-24432', name: 'BioGuard Calcium Hardness 25lb', category: 'Chemicals', subcategory: 'Specialty', price: 89.00, unit: 'BK', manufacturer: 'BioGuard' },
  { sku: 'CHEM-SP-010', heritageNumber: 'ORE-24501', name: 'Orenda CV-700 Enzyme 1qt', category: 'Chemicals', subcategory: 'Specialty', price: 44.99, unit: 'EA', manufacturer: 'Orenda' },
  { sku: 'CHEM-SP-011', heritageNumber: 'ORE-24502', name: 'Orenda CV-700 Enzyme 1gal', category: 'Chemicals', subcategory: 'Specialty', price: 149.00, unit: 'EA', manufacturer: 'Orenda' },
  { sku: 'CHEM-SP-012', heritageNumber: 'ORE-24510', name: 'Orenda SC-1000 Scale & Metal 1qt', category: 'Chemicals', subcategory: 'Specialty', price: 39.99, unit: 'EA', manufacturer: 'Orenda' },
  { sku: 'CHEM-SP-013', heritageNumber: 'ORE-24511', name: 'Orenda SC-1000 Scale & Metal 1gal', category: 'Chemicals', subcategory: 'Specialty', price: 129.00, unit: 'EA', manufacturer: 'Orenda' },
  { sku: 'CHEM-SP-014', heritageNumber: 'ORE-24520', name: 'Orenda PR-10000 Phosphate Rem 1qt', category: 'Chemicals', subcategory: 'Specialty', price: 29.99, unit: 'EA', manufacturer: 'Orenda' },
  { sku: 'CHEM-SP-015', heritageNumber: 'ORE-24521', name: 'Orenda PR-10000 Phosphate Rem 1gal', category: 'Chemicals', subcategory: 'Specialty', price: 99.00, unit: 'EA', manufacturer: 'Orenda' },
  { sku: 'CHEM-SP-016', heritageNumber: 'NAT-24601', name: 'Natural Chemistry Pool First Aid 2L', category: 'Chemicals', subcategory: 'Specialty', price: 34.99, unit: 'EA', manufacturer: 'Natural Chemistry' },
  { sku: 'CHEM-SP-017', heritageNumber: 'NAT-24602', name: 'Natural Chemistry Pool Perfect 3L', category: 'Chemicals', subcategory: 'Specialty', price: 49.99, unit: 'EA', manufacturer: 'Natural Chemistry' },
  { sku: 'CHEM-SP-018', heritageNumber: 'NAT-24610', name: 'Natural Chemistry Phosphate Free 3L', category: 'Chemicals', subcategory: 'Specialty', price: 54.99, unit: 'EA', manufacturer: 'Natural Chemistry' },
  { sku: 'CHEM-SP-019', heritageNumber: 'NAT-24611', name: 'Natural Chemistry Metal Free 1L', category: 'Chemicals', subcategory: 'Specialty', price: 24.99, unit: 'EA', manufacturer: 'Natural Chemistry' },
  { sku: 'CHEM-SP-020', heritageNumber: 'PPG-42601', name: 'PPG Pool Salt 40lb', category: 'Chemicals', subcategory: 'Specialty', price: 12.99, unit: 'BG', manufacturer: 'PPG' },

  // CLEANERS - Robotic (40 products)
  { sku: 'CLN-RB-001', heritageNumber: 'DOL-99996133', name: 'Dolphin Nautilus CC Plus', category: 'Cleaners', subcategory: 'Robotic', price: 1099.00, unit: 'EA', manufacturer: 'Dolphin' },
  { sku: 'CLN-RB-002', heritageNumber: 'DOL-99996148', name: 'Dolphin Nautilus CC Supreme', category: 'Cleaners', subcategory: 'Robotic', price: 1399.00, unit: 'EA', manufacturer: 'Dolphin' },
  { sku: 'CLN-RB-003', heritageNumber: 'DOL-99996151', name: 'Dolphin Escape', category: 'Cleaners', subcategory: 'Robotic', price: 799.00, unit: 'EA', manufacturer: 'Dolphin' },
  { sku: 'CLN-RB-004', heritageNumber: 'DOL-99996155', name: 'Dolphin Triton PS Plus', category: 'Cleaners', subcategory: 'Robotic', price: 1299.00, unit: 'EA', manufacturer: 'Dolphin' },
  { sku: 'CLN-RB-005', heritageNumber: 'DOL-99996156', name: 'Dolphin Premier', category: 'Cleaners', subcategory: 'Robotic', price: 1599.00, unit: 'EA', manufacturer: 'Dolphin' },
  { sku: 'CLN-RB-006', heritageNumber: 'DOL-99996170', name: 'Dolphin Sigma', category: 'Cleaners', subcategory: 'Robotic', price: 1899.00, unit: 'EA', manufacturer: 'Dolphin' },
  { sku: 'CLN-RB-007', heritageNumber: 'DOL-99996180', name: 'Dolphin Quantum', category: 'Cleaners', subcategory: 'Robotic', price: 2199.00, unit: 'EA', manufacturer: 'Dolphin' },
  { sku: 'CLN-RB-008', heritageNumber: 'HAY-RC9990GR', name: 'Hayward TigerShark QC', category: 'Cleaners', subcategory: 'Robotic', price: 1349.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CLN-RB-009', heritageNumber: 'HAY-RC9955GR', name: 'Hayward SharkVac XL', category: 'Cleaners', subcategory: 'Robotic', price: 949.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CLN-RB-010', heritageNumber: 'HAY-RC9742WCCUBY', name: 'Hayward AquaVac 650', category: 'Cleaners', subcategory: 'Robotic', price: 1499.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CLN-RB-011', heritageNumber: 'POL-F9550', name: 'Polaris F9550 Sport 4WD', category: 'Cleaners', subcategory: 'Robotic', price: 1799.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-RB-012', heritageNumber: 'POL-F9450', name: 'Polaris F9450 Sport', category: 'Cleaners', subcategory: 'Robotic', price: 1399.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-RB-013', heritageNumber: 'POL-F9350', name: 'Polaris F9350 Sport', category: 'Cleaners', subcategory: 'Robotic', price: 1199.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-RB-014', heritageNumber: 'PEN-360031', name: 'Pentair Kreepy Krauly Prowler 920', category: 'Cleaners', subcategory: 'Robotic', price: 1099.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CLN-RB-015', heritageNumber: 'PEN-360032', name: 'Pentair Prowler 930 W Energy', category: 'Cleaners', subcategory: 'Robotic', price: 1349.00, unit: 'EA', manufacturer: 'Pentair' },

  // CLEANERS - Pressure Side (25 products)
  { sku: 'CLN-PR-001', heritageNumber: 'POL-F1', name: 'Polaris Vac-Sweep 360', category: 'Cleaners', subcategory: 'Pressure Side', price: 549.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-PR-002', heritageNumber: 'POL-F5', name: 'Polaris Vac-Sweep 280', category: 'Cleaners', subcategory: 'Pressure Side', price: 699.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-PR-003', heritageNumber: 'POL-F3', name: 'Polaris Vac-Sweep 380', category: 'Cleaners', subcategory: 'Pressure Side', price: 849.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-PR-004', heritageNumber: 'POL-F7', name: 'Polaris Vac-Sweep 3900 Sport', category: 'Cleaners', subcategory: 'Pressure Side', price: 949.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-PR-005', heritageNumber: 'POL-F9', name: 'Polaris Vac-Sweep 480 Pro', category: 'Cleaners', subcategory: 'Pressure Side', price: 1099.00, unit: 'EA', manufacturer: 'Polaris' },
  { sku: 'CLN-PR-006', heritageNumber: 'PEN-360040', name: 'Pentair Legend Platinum', category: 'Cleaners', subcategory: 'Pressure Side', price: 799.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CLN-PR-007', heritageNumber: 'HAY-DVP4', name: 'Hayward Phoenix 4X', category: 'Cleaners', subcategory: 'Pressure Side', price: 599.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CLN-PR-008', heritageNumber: 'HAY-DVP2', name: 'Hayward Phoenix 2X', category: 'Cleaners', subcategory: 'Pressure Side', price: 449.00, unit: 'EA', manufacturer: 'Hayward' },

  // CLEANERS - Suction Side (25 products)
  { sku: 'CLN-SC-001', heritageNumber: 'HAY-925ADC', name: 'Hayward PoolVac XL', category: 'Cleaners', subcategory: 'Suction Side', price: 449.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CLN-SC-002', heritageNumber: 'HAY-W3925ADC', name: 'Hayward Navigator Pro', category: 'Cleaners', subcategory: 'Suction Side', price: 349.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CLN-SC-003', heritageNumber: 'HAY-PEARL', name: 'Hayward Pearl', category: 'Cleaners', subcategory: 'Suction Side', price: 549.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'CLN-SC-004', heritageNumber: 'ZOD-MX6', name: 'Zodiac MX6 Suction Cleaner', category: 'Cleaners', subcategory: 'Suction Side', price: 399.00, unit: 'EA', manufacturer: 'Zodiac' },
  { sku: 'CLN-SC-005', heritageNumber: 'ZOD-MX8', name: 'Zodiac MX8 Elite Suction', category: 'Cleaners', subcategory: 'Suction Side', price: 549.00, unit: 'EA', manufacturer: 'Zodiac' },
  { sku: 'CLN-SC-006', heritageNumber: 'PEN-360042', name: 'Pentair Kreepy Krauly', category: 'Cleaners', subcategory: 'Suction Side', price: 299.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CLN-SC-007', heritageNumber: 'PEN-360043', name: 'Pentair Great White', category: 'Cleaners', subcategory: 'Suction Side', price: 349.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'CLN-SC-008', heritageNumber: 'ZOD-W70482', name: 'Zodiac Baracuda G3', category: 'Cleaners', subcategory: 'Suction Side', price: 279.00, unit: 'EA', manufacturer: 'Zodiac' },
  { sku: 'CLN-SC-009', heritageNumber: 'ZOD-W70472', name: 'Zodiac Baracuda G4', category: 'Cleaners', subcategory: 'Suction Side', price: 399.00, unit: 'EA', manufacturer: 'Zodiac' },

  // LIGHTING - LED (50 products)
  { sku: 'LITE-LED-001', heritageNumber: 'HAY-LPCUS11030', name: 'Hayward ColorLogic 4.0 LED 12V', category: 'Lighting', subcategory: 'LED Pool Lights', price: 549.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'LITE-LED-002', heritageNumber: 'HAY-LPCUS11050', name: 'Hayward ColorLogic 4.0 LED 50ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 599.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'LITE-LED-003', heritageNumber: 'HAY-LPCUS11100', name: 'Hayward ColorLogic 4.0 LED 100ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 649.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'LITE-LED-004', heritageNumber: 'HAY-LSCUS11030', name: 'Hayward ColorLogic LED Spa 30ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 449.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'LITE-LED-005', heritageNumber: 'PEN-601011', name: 'Pentair IntelliBrite 5G Color', category: 'Lighting', subcategory: 'LED Pool Lights', price: 599.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'LITE-LED-006', heritageNumber: 'PEN-601012', name: 'Pentair IntelliBrite 5G 50ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 649.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'LITE-LED-007', heritageNumber: 'PEN-601013', name: 'Pentair IntelliBrite 5G 100ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 699.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'LITE-LED-008', heritageNumber: 'PEN-640122', name: 'Pentair MicroBrite LED Color', category: 'Lighting', subcategory: 'LED Pool Lights', price: 299.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'LITE-LED-009', heritageNumber: 'JAN-CPHVLEDS100', name: 'Jandy Pro Series LED 100ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 579.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'LITE-LED-010', heritageNumber: 'JAN-CPHVLEDS50', name: 'Jandy Pro Series LED 50ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 529.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'LITE-LED-011', heritageNumber: 'JAN-WPHV500WS100', name: 'Jandy WaterColors LED 100ft', category: 'Lighting', subcategory: 'LED Pool Lights', price: 599.00, unit: 'EA', manufacturer: 'Jandy' },
  { sku: 'LITE-LED-012', heritageNumber: 'GLO-4401210', name: 'GloFlo LED Light 1.5" Fitting', category: 'Lighting', subcategory: 'LED Pool Lights', price: 199.00, unit: 'EA', manufacturer: 'GloFlo' },
  { sku: 'LITE-LED-013', heritageNumber: 'GLO-4401211', name: 'GloFlo Nicheless LED Light', category: 'Lighting', subcategory: 'LED Pool Lights', price: 249.00, unit: 'EA', manufacturer: 'GloFlo' },

  // LIGHTING - Transformers (15 products)
  { sku: 'LITE-TR-001', heritageNumber: 'INT-PX600', name: 'Intermatic PX600 600W Transformer', category: 'Lighting', subcategory: 'Transformers', price: 299.00, unit: 'EA', manufacturer: 'Intermatic' },
  { sku: 'LITE-TR-002', heritageNumber: 'INT-PX300', name: 'Intermatic PX300 300W Transformer', category: 'Lighting', subcategory: 'Transformers', price: 199.00, unit: 'EA', manufacturer: 'Intermatic' },
  { sku: 'LITE-TR-003', heritageNumber: 'INT-PX100', name: 'Intermatic PX100 100W Transformer', category: 'Lighting', subcategory: 'Transformers', price: 129.00, unit: 'EA', manufacturer: 'Intermatic' },
  { sku: 'LITE-TR-004', heritageNumber: 'HAY-LTBUY11300', name: 'Hayward LED Transformer 300W', category: 'Lighting', subcategory: 'Transformers', price: 249.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'LITE-TR-005', heritageNumber: 'PEN-619963', name: 'Pentair 300W Transformer', category: 'Lighting', subcategory: 'Transformers', price: 229.00, unit: 'EA', manufacturer: 'Pentair' },

  // COVERS - Safety (20 products)
  { sku: 'COV-SF-001', heritageNumber: 'LOO-SC16', name: 'Loop-Loc 16x32 Mesh Safety Cover', category: 'Covers', subcategory: 'Safety Covers', price: 1299.00, unit: 'EA', manufacturer: 'Loop-Loc' },
  { sku: 'COV-SF-002', heritageNumber: 'LOO-SC18', name: 'Loop-Loc 18x36 Mesh Safety Cover', category: 'Covers', subcategory: 'Safety Covers', price: 1549.00, unit: 'EA', manufacturer: 'Loop-Loc' },
  { sku: 'COV-SF-003', heritageNumber: 'LOO-SC20', name: 'Loop-Loc 20x40 Mesh Safety Cover', category: 'Covers', subcategory: 'Safety Covers', price: 1899.00, unit: 'EA', manufacturer: 'Loop-Loc' },
  { sku: 'COV-SF-004', heritageNumber: 'LOO-SC20S', name: 'Loop-Loc 20x40 Solid Safety Cover', category: 'Covers', subcategory: 'Safety Covers', price: 2199.00, unit: 'EA', manufacturer: 'Loop-Loc' },
  { sku: 'COV-SF-005', heritageNumber: 'MYP-SC16', name: 'Meyco 16x32 PermaGuard Solid', category: 'Covers', subcategory: 'Safety Covers', price: 1399.00, unit: 'EA', manufacturer: 'Meyco' },
  { sku: 'COV-SF-006', heritageNumber: 'MYP-SC18', name: 'Meyco 18x36 PermaGuard Solid', category: 'Covers', subcategory: 'Safety Covers', price: 1699.00, unit: 'EA', manufacturer: 'Meyco' },
  { sku: 'COV-SF-007', heritageNumber: 'MYP-SC20', name: 'Meyco 20x40 PermaGuard Solid', category: 'Covers', subcategory: 'Safety Covers', price: 1999.00, unit: 'EA', manufacturer: 'Meyco' },
  { sku: 'COV-SF-008', heritageNumber: 'GLI-SC1632', name: 'GLI 16x32 ProMesh Safety Cover', category: 'Covers', subcategory: 'Safety Covers', price: 1199.00, unit: 'EA', manufacturer: 'GLI' },

  // COVERS - Solar (15 products)
  { sku: 'COV-SL-001', heritageNumber: 'BLU-SB1624', name: 'Blue Wave 16x24 Solar Blanket', category: 'Covers', subcategory: 'Solar Covers', price: 79.00, unit: 'EA', manufacturer: 'Blue Wave' },
  { sku: 'COV-SL-002', heritageNumber: 'BLU-SB1632', name: 'Blue Wave 16x32 Solar Blanket', category: 'Covers', subcategory: 'Solar Covers', price: 99.00, unit: 'EA', manufacturer: 'Blue Wave' },
  { sku: 'COV-SL-003', heritageNumber: 'BLU-SB1836', name: 'Blue Wave 18x36 Solar Blanket', category: 'Covers', subcategory: 'Solar Covers', price: 129.00, unit: 'EA', manufacturer: 'Blue Wave' },
  { sku: 'COV-SL-004', heritageNumber: 'BLU-SB2040', name: 'Blue Wave 20x40 Solar Blanket', category: 'Covers', subcategory: 'Solar Covers', price: 159.00, unit: 'EA', manufacturer: 'Blue Wave' },
  { sku: 'COV-SL-005', heritageNumber: 'SUN-SR1832', name: 'Sun2Solar 18x32 Solar Cover', category: 'Covers', subcategory: 'Solar Covers', price: 149.00, unit: 'EA', manufacturer: 'Sun2Solar' },

  // SAFETY EQUIPMENT (30 products)
  { sku: 'SAFE-001', heritageNumber: 'PF-KP180', name: 'Pool Fence DIY 4ft Section Black', category: 'Safety', subcategory: 'Pool Fencing', price: 149.00, unit: 'EA', manufacturer: 'Pool Fence DIY' },
  { sku: 'SAFE-002', heritageNumber: 'PF-KP185', name: 'Pool Fence DIY 5ft Section Black', category: 'Safety', subcategory: 'Pool Fencing', price: 179.00, unit: 'EA', manufacturer: 'Pool Fence DIY' },
  { sku: 'SAFE-003', heritageNumber: 'PF-GATE36', name: 'Pool Fence Gate 36" Self-Closing', category: 'Safety', subcategory: 'Pool Fencing', price: 349.00, unit: 'EA', manufacturer: 'Pool Fence DIY' },
  { sku: 'SAFE-004', heritageNumber: 'PF-GATE48', name: 'Pool Fence Gate 48" Self-Closing', category: 'Safety', subcategory: 'Pool Fencing', price: 399.00, unit: 'EA', manufacturer: 'Pool Fence DIY' },
  { sku: 'SAFE-005', heritageNumber: 'POO-AL100', name: 'Pool Alarm Immersion Detection', category: 'Safety', subcategory: 'Alarms', price: 199.00, unit: 'EA', manufacturer: 'Poolguard' },
  { sku: 'SAFE-006', heritageNumber: 'POO-AL200', name: 'Pool Alarm Surface Wave', category: 'Safety', subcategory: 'Alarms', price: 249.00, unit: 'EA', manufacturer: 'Poolguard' },
  { sku: 'SAFE-007', heritageNumber: 'POO-AL300', name: 'Pool Alarm Gate/Door', category: 'Safety', subcategory: 'Alarms', price: 149.00, unit: 'EA', manufacturer: 'Poolguard' },
  { sku: 'SAFE-008', heritageNumber: 'TAY-K2006', name: 'Taylor Complete Test Kit K-2006', category: 'Safety', subcategory: 'Testing', price: 89.00, unit: 'EA', manufacturer: 'Taylor' },
  { sku: 'SAFE-009', heritageNumber: 'TAY-K2005', name: 'Taylor Basic Test Kit K-2005', category: 'Safety', subcategory: 'Testing', price: 59.00, unit: 'EA', manufacturer: 'Taylor' },
  { sku: 'SAFE-010', heritageNumber: 'HAL-SPIN', name: 'Hach Spin Touch Lab', category: 'Safety', subcategory: 'Testing', price: 549.00, unit: 'EA', manufacturer: 'Hach' },
  { sku: 'SAFE-011', heritageNumber: 'LAM-2050', name: 'LaMotte ColorQ Pro 7', category: 'Safety', subcategory: 'Testing', price: 449.00, unit: 'EA', manufacturer: 'LaMotte' },
  { sku: 'SAFE-012', heritageNumber: 'LAM-2060', name: 'LaMotte ColorQ Pro 11', category: 'Safety', subcategory: 'Testing', price: 549.00, unit: 'EA', manufacturer: 'LaMotte' },

  // PLUMBING (80 products)
  { sku: 'PLMB-001', heritageNumber: 'PVC-S40-150', name: 'PVC Pipe Sch40 1.5" x 10ft', category: 'Plumbing', subcategory: 'Pipe', price: 8.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-002', heritageNumber: 'PVC-S40-200', name: 'PVC Pipe Sch40 2" x 10ft', category: 'Plumbing', subcategory: 'Pipe', price: 12.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-003', heritageNumber: 'PVC-S40-250', name: 'PVC Pipe Sch40 2.5" x 10ft', category: 'Plumbing', subcategory: 'Pipe', price: 18.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-004', heritageNumber: 'PVC-S40-300', name: 'PVC Pipe Sch40 3" x 10ft', category: 'Plumbing', subcategory: 'Pipe', price: 24.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-005', heritageNumber: 'PVC-S80-150', name: 'PVC Pipe Sch80 1.5" x 10ft', category: 'Plumbing', subcategory: 'Pipe', price: 14.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-006', heritageNumber: 'PVC-S80-200', name: 'PVC Pipe Sch80 2" x 10ft', category: 'Plumbing', subcategory: 'Pipe', price: 19.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-007', heritageNumber: 'FIT-EL90-150', name: '90 Elbow PVC 1.5" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 1.49, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-008', heritageNumber: 'FIT-EL90-200', name: '90 Elbow PVC 2" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 2.49, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-009', heritageNumber: 'FIT-EL45-150', name: '45 Elbow PVC 1.5" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 1.29, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-010', heritageNumber: 'FIT-EL45-200', name: '45 Elbow PVC 2" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 2.29, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-011', heritageNumber: 'FIT-TEE-150', name: 'Tee PVC 1.5" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 1.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-012', heritageNumber: 'FIT-TEE-200', name: 'Tee PVC 2" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 2.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-013', heritageNumber: 'FIT-CPL-150', name: 'Coupling PVC 1.5" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 0.79, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-014', heritageNumber: 'FIT-CPL-200', name: 'Coupling PVC 2" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 1.29, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-015', heritageNumber: 'FIT-UNI-150', name: 'Union PVC 1.5" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 8.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-016', heritageNumber: 'FIT-UNI-200', name: 'Union PVC 2" Slip', category: 'Plumbing', subcategory: 'Fittings', price: 12.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-017', heritageNumber: 'FIT-MTA-150', name: 'Male Threaded Adapter 1.5"', category: 'Plumbing', subcategory: 'Fittings', price: 1.49, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-018', heritageNumber: 'FIT-MTA-200', name: 'Male Threaded Adapter 2"', category: 'Plumbing', subcategory: 'Fittings', price: 2.49, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-019', heritageNumber: 'FIT-FTA-150', name: 'Female Threaded Adapter 1.5"', category: 'Plumbing', subcategory: 'Fittings', price: 1.79, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-020', heritageNumber: 'FIT-FTA-200', name: 'Female Threaded Adapter 2"', category: 'Plumbing', subcategory: 'Fittings', price: 2.79, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-021', heritageNumber: 'FIT-RED-2015', name: 'Reducer Bushing 2" x 1.5"', category: 'Plumbing', subcategory: 'Fittings', price: 1.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-022', heritageNumber: 'FIT-RED-2520', name: 'Reducer Bushing 2.5" x 2"', category: 'Plumbing', subcategory: 'Fittings', price: 2.99, unit: 'EA', manufacturer: 'Generic' },
  { sku: 'PLMB-023', heritageNumber: 'GLU-0120', name: 'PVC Glue Clear 1 Quart', category: 'Plumbing', subcategory: 'Adhesives', price: 24.99, unit: 'EA', manufacturer: 'Oatey' },
  { sku: 'PLMB-024', heritageNumber: 'GLU-0121', name: 'PVC Glue Blue Medium 1qt', category: 'Plumbing', subcategory: 'Adhesives', price: 29.99, unit: 'EA', manufacturer: 'Oatey' },
  { sku: 'PLMB-025', heritageNumber: 'GLU-0130', name: 'PVC Primer Purple 1 Quart', category: 'Plumbing', subcategory: 'Adhesives', price: 19.99, unit: 'EA', manufacturer: 'Oatey' },
  { sku: 'PLMB-026', heritageNumber: 'GLU-0140', name: 'PVC Glue Hot Blue 1 Quart', category: 'Plumbing', subcategory: 'Adhesives', price: 34.99, unit: 'EA', manufacturer: 'Christy' },
  { sku: 'PLMB-027', heritageNumber: 'FLX-200', name: 'Flex PVC 2" x 50ft Roll', category: 'Plumbing', subcategory: 'Flexible Pipe', price: 89.00, unit: 'RL', manufacturer: 'Spears' },
  { sku: 'PLMB-028', heritageNumber: 'FLX-150', name: 'Flex PVC 1.5" x 50ft Roll', category: 'Plumbing', subcategory: 'Flexible Pipe', price: 69.00, unit: 'RL', manufacturer: 'Spears' },

  // MOTORS - Replacement (40 products)
  { sku: 'MOTR-001', heritageNumber: 'CEN-B625', name: 'Century B625 3/4HP Pool Motor', category: 'Motors', subcategory: 'Replacement Motors', price: 199.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-002', heritageNumber: 'CEN-B128', name: 'Century B128 1HP Pool Motor', category: 'Motors', subcategory: 'Replacement Motors', price: 249.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-003', heritageNumber: 'CEN-B129', name: 'Century B129 1.5HP Pool Motor', category: 'Motors', subcategory: 'Replacement Motors', price: 299.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-004', heritageNumber: 'CEN-B130', name: 'Century B130 2HP Pool Motor', category: 'Motors', subcategory: 'Replacement Motors', price: 349.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-005', heritageNumber: 'CEN-B2841', name: 'Century B2841 1HP 56Y Frame', category: 'Motors', subcategory: 'Replacement Motors', price: 279.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-006', heritageNumber: 'CEN-B2842', name: 'Century B2842 1.5HP 56Y Frame', category: 'Motors', subcategory: 'Replacement Motors', price: 329.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-007', heritageNumber: 'CEN-B2843', name: 'Century B2843 2HP 56Y Frame', category: 'Motors', subcategory: 'Replacement Motors', price: 379.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-008', heritageNumber: 'CEN-B2854', name: 'Century B2854 1.5HP 2-Speed', category: 'Motors', subcategory: 'Replacement Motors', price: 399.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-009', heritageNumber: 'CEN-B2858', name: 'Century B2858 2HP 2-Speed', category: 'Motors', subcategory: 'Replacement Motors', price: 449.00, unit: 'EA', manufacturer: 'Century' },
  { sku: 'MOTR-010', heritageNumber: 'USM-T1102', name: 'US Motors T1102 1HP 48Y', category: 'Motors', subcategory: 'Replacement Motors', price: 259.00, unit: 'EA', manufacturer: 'US Motors' },
  { sku: 'MOTR-011', heritageNumber: 'USM-T1152', name: 'US Motors T1152 1.5HP 48Y', category: 'Motors', subcategory: 'Replacement Motors', price: 309.00, unit: 'EA', manufacturer: 'US Motors' },
  { sku: 'MOTR-012', heritageNumber: 'USM-T1202', name: 'US Motors T1202 2HP 48Y', category: 'Motors', subcategory: 'Replacement Motors', price: 359.00, unit: 'EA', manufacturer: 'US Motors' },
  { sku: 'MOTR-013', heritageNumber: 'RAG-ECM16CU', name: 'Regal Beloit ECM 1.65HP VS Motor', category: 'Motors', subcategory: 'Variable Speed Motors', price: 749.00, unit: 'EA', manufacturer: 'Regal Beloit' },
  { sku: 'MOTR-014', heritageNumber: 'RAG-ECM27CU', name: 'Regal Beloit ECM 2.7HP VS Motor', category: 'Motors', subcategory: 'Variable Speed Motors', price: 899.00, unit: 'EA', manufacturer: 'Regal Beloit' },

  // PARTS - Pump Parts (60 products)
  { sku: 'PART-PP-001', heritageNumber: 'HAY-SPX1600Z2', name: 'Hayward Super Pump Impeller 1HP', category: 'Parts', subcategory: 'Pump Parts', price: 49.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-002', heritageNumber: 'HAY-SPX1620Z2', name: 'Hayward Super Pump Impeller 1.5HP', category: 'Parts', subcategory: 'Pump Parts', price: 54.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-003', heritageNumber: 'HAY-SPX1600Z4', name: 'Hayward Super Pump Impeller 2HP', category: 'Parts', subcategory: 'Pump Parts', price: 59.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-004', heritageNumber: 'HAY-SPX1600R', name: 'Hayward Super Pump Lid Gasket', category: 'Parts', subcategory: 'Pump Parts', price: 12.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-005', heritageNumber: 'HAY-SPX1600T', name: 'Hayward Super Pump Strainer Lid', category: 'Parts', subcategory: 'Pump Parts', price: 29.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-006', heritageNumber: 'HAY-SPX1600Y', name: 'Hayward Super Pump Diffuser', category: 'Parts', subcategory: 'Pump Parts', price: 24.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-007', heritageNumber: 'HAY-SPX1600S', name: 'Hayward Super Pump Strainer Basket', category: 'Parts', subcategory: 'Pump Parts', price: 19.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-008', heritageNumber: 'HAY-SPX1600V', name: 'Hayward Super Pump Seal Assembly', category: 'Parts', subcategory: 'Pump Parts', price: 24.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-PP-009', heritageNumber: 'PEN-355369', name: 'Pentair WhisperFlo Impeller 1HP', category: 'Parts', subcategory: 'Pump Parts', price: 54.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-PP-010', heritageNumber: 'PEN-355389', name: 'Pentair WhisperFlo Impeller 1.5HP', category: 'Parts', subcategory: 'Pump Parts', price: 59.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-PP-011', heritageNumber: 'PEN-355429', name: 'Pentair WhisperFlo Impeller 2HP', category: 'Parts', subcategory: 'Pump Parts', price: 64.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-PP-012', heritageNumber: 'PEN-357149', name: 'Pentair Lid O-Ring WhisperFlo', category: 'Parts', subcategory: 'Pump Parts', price: 14.99, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-PP-013', heritageNumber: 'PEN-357255', name: 'Pentair Strainer Lid WhisperFlo', category: 'Parts', subcategory: 'Pump Parts', price: 34.99, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-PP-014', heritageNumber: 'PEN-355667', name: 'Pentair Seal Assembly WhisperFlo', category: 'Parts', subcategory: 'Pump Parts', price: 29.99, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-PP-015', heritageNumber: 'JAN-R0445900', name: 'Jandy FloPro Impeller 1HP', category: 'Parts', subcategory: 'Pump Parts', price: 49.00, unit: 'EA', manufacturer: 'Jandy' },

  // PARTS - Filter Parts (50 products)
  { sku: 'PART-FP-001', heritageNumber: 'HAY-CCX1000D', name: 'Hayward Filter Air Relief Valve', category: 'Parts', subcategory: 'Filter Parts', price: 19.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-FP-002', heritageNumber: 'HAY-CCX1000Z5', name: 'Hayward Filter Lid O-Ring', category: 'Parts', subcategory: 'Filter Parts', price: 24.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-FP-003', heritageNumber: 'HAY-DEX2400Z5', name: 'Hayward Pro-Grid Lid O-Ring', category: 'Parts', subcategory: 'Filter Parts', price: 29.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-FP-004', heritageNumber: 'HAY-SX200Z2', name: 'Hayward Sand Filter Lateral', category: 'Parts', subcategory: 'Filter Parts', price: 12.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-FP-005', heritageNumber: 'HAY-SX200Z4', name: 'Hayward Sand Filter Standpipe', category: 'Parts', subcategory: 'Filter Parts', price: 34.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-FP-006', heritageNumber: 'HAY-SP0714T', name: 'Hayward Multiport Valve 1.5"', category: 'Parts', subcategory: 'Filter Parts', price: 149.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-FP-007', heritageNumber: 'HAY-SP0715', name: 'Hayward Multiport Valve 2"', category: 'Parts', subcategory: 'Filter Parts', price: 179.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-FP-008', heritageNumber: 'PEN-261050', name: 'Pentair Multiport Valve 1.5"', category: 'Parts', subcategory: 'Filter Parts', price: 159.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-FP-009', heritageNumber: 'PEN-261055', name: 'Pentair Multiport Valve 2"', category: 'Parts', subcategory: 'Filter Parts', price: 189.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-FP-010', heritageNumber: 'PEN-178561', name: 'Pentair Filter Lid O-Ring', category: 'Parts', subcategory: 'Filter Parts', price: 24.99, unit: 'EA', manufacturer: 'Pentair' },

  // PARTS - Heater Parts (40 products)
  { sku: 'PART-HP-001', heritageNumber: 'HAY-IDXIGN1930', name: 'Hayward H-Series Igniter', category: 'Parts', subcategory: 'Heater Parts', price: 89.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-HP-002', heritageNumber: 'HAY-FDXLGSV0001', name: 'Hayward Gas Valve Universal', category: 'Parts', subcategory: 'Heater Parts', price: 349.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-HP-003', heritageNumber: 'HAY-FDXLHXA1400', name: 'Hayward Heat Exchanger Assembly', category: 'Parts', subcategory: 'Heater Parts', price: 899.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-HP-004', heritageNumber: 'HAY-IDXL2TRF1930', name: 'Hayward Thermal Regulator', category: 'Parts', subcategory: 'Heater Parts', price: 79.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-HP-005', heritageNumber: 'HAY-IDXLFLS1930', name: 'Hayward Flow Switch', category: 'Parts', subcategory: 'Heater Parts', price: 69.00, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'PART-HP-006', heritageNumber: 'PEN-42002-0007', name: 'Pentair MasterTemp Igniter', category: 'Parts', subcategory: 'Heater Parts', price: 99.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-HP-007', heritageNumber: 'PEN-42001-0051', name: 'Pentair MasterTemp Control Board', category: 'Parts', subcategory: 'Heater Parts', price: 449.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-HP-008', heritageNumber: 'PEN-77707-0016', name: 'Pentair Gas Valve MasterTemp', category: 'Parts', subcategory: 'Heater Parts', price: 399.00, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'PART-HP-009', heritageNumber: 'RAY-010349F', name: 'Raypak Igniter Assembly', category: 'Parts', subcategory: 'Heater Parts', price: 79.00, unit: 'EA', manufacturer: 'Raypak' },
  { sku: 'PART-HP-010', heritageNumber: 'RAY-003900F', name: 'Raypak Gas Valve', category: 'Parts', subcategory: 'Heater Parts', price: 329.00, unit: 'EA', manufacturer: 'Raypak' },

  // TOOLS (50 products)
  { sku: 'TOOL-001', heritageNumber: 'CHA-T100', name: 'Champion Pole 12ft Telescopic', category: 'Tools', subcategory: 'Poles', price: 49.00, unit: 'EA', manufacturer: 'Champion' },
  { sku: 'TOOL-002', heritageNumber: 'CHA-T160', name: 'Champion Pole 16ft Telescopic', category: 'Tools', subcategory: 'Poles', price: 69.00, unit: 'EA', manufacturer: 'Champion' },
  { sku: 'TOOL-003', heritageNumber: 'CHA-T200', name: 'Champion Pole 20ft Heavy Duty', category: 'Tools', subcategory: 'Poles', price: 99.00, unit: 'EA', manufacturer: 'Champion' },
  { sku: 'TOOL-004', heritageNumber: 'PRO-P12', name: 'ProTuff 12ft Pole Aluminum', category: 'Tools', subcategory: 'Poles', price: 59.00, unit: 'EA', manufacturer: 'ProTuff' },
  { sku: 'TOOL-005', heritageNumber: 'PRO-P16', name: 'ProTuff 16ft Pole Aluminum', category: 'Tools', subcategory: 'Poles', price: 79.00, unit: 'EA', manufacturer: 'ProTuff' },
  { sku: 'TOOL-006', heritageNumber: 'HAY-SP1096', name: 'Hayward Leaf Skimmer Net', category: 'Tools', subcategory: 'Nets', price: 19.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'TOOL-007', heritageNumber: 'HAY-SP1098', name: 'Hayward Deep Bag Net', category: 'Tools', subcategory: 'Nets', price: 24.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'TOOL-008', heritageNumber: 'PRO-SN18', name: 'ProTuff Pro Leaf Rake 18"', category: 'Tools', subcategory: 'Nets', price: 34.99, unit: 'EA', manufacturer: 'ProTuff' },
  { sku: 'TOOL-009', heritageNumber: 'PRO-SN24', name: 'ProTuff Pro Leaf Rake 24"', category: 'Tools', subcategory: 'Nets', price: 44.99, unit: 'EA', manufacturer: 'ProTuff' },
  { sku: 'TOOL-010', heritageNumber: 'PRO-BR18', name: 'ProTuff Wall Brush 18" Aluminum', category: 'Tools', subcategory: 'Brushes', price: 29.99, unit: 'EA', manufacturer: 'ProTuff' },
  { sku: 'TOOL-011', heritageNumber: 'PRO-BR24', name: 'ProTuff Wall Brush 24" Aluminum', category: 'Tools', subcategory: 'Brushes', price: 39.99, unit: 'EA', manufacturer: 'ProTuff' },
  { sku: 'TOOL-012', heritageNumber: 'PRO-BRSS', name: 'ProTuff Stainless Steel Brush 18"', category: 'Tools', subcategory: 'Brushes', price: 49.99, unit: 'EA', manufacturer: 'ProTuff' },
  { sku: 'TOOL-013', heritageNumber: 'HAY-SP1068', name: 'Hayward Pool Vacuum Head 14"', category: 'Tools', subcategory: 'Vacuums', price: 34.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'TOOL-014', heritageNumber: 'HAY-SP1106', name: 'Hayward Weighted Vacuum Head', category: 'Tools', subcategory: 'Vacuums', price: 49.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'TOOL-015', heritageNumber: 'PEN-R201406', name: 'Pentair Vacuum Hose 1.5" x 40ft', category: 'Tools', subcategory: 'Hoses', price: 69.99, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'TOOL-016', heritageNumber: 'PEN-R201407', name: 'Pentair Vacuum Hose 1.5" x 50ft', category: 'Tools', subcategory: 'Hoses', price: 84.99, unit: 'EA', manufacturer: 'Pentair' },
  { sku: 'TOOL-017', heritageNumber: 'HAY-AX5004C', name: 'Hayward Backwash Hose 2" x 25ft', category: 'Tools', subcategory: 'Hoses', price: 29.99, unit: 'EA', manufacturer: 'Hayward' },
  { sku: 'TOOL-018', heritageNumber: 'HAY-AX5004D', name: 'Hayward Backwash Hose 2" x 50ft', category: 'Tools', subcategory: 'Hoses', price: 49.99, unit: 'EA', manufacturer: 'Hayward' },

  // LABOR (30 products)
  { sku: 'LABOR-001', heritageNumber: 'LBR-STD', name: 'Standard Labor (per hour)', category: 'Labor', subcategory: 'Hourly', price: 95.00, unit: 'HR', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-002', heritageNumber: 'LBR-EMR', name: 'Emergency Labor (per hour)', category: 'Labor', subcategory: 'Hourly', price: 145.00, unit: 'HR', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-003', heritageNumber: 'LBR-AFHR', name: 'After Hours Labor (per hour)', category: 'Labor', subcategory: 'Hourly', price: 125.00, unit: 'HR', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-004', heritageNumber: 'LBR-WKND', name: 'Weekend Labor (per hour)', category: 'Labor', subcategory: 'Hourly', price: 135.00, unit: 'HR', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-005', heritageNumber: 'LBR-PUMP', name: 'Pump Installation', category: 'Labor', subcategory: 'Installation', price: 350.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-006', heritageNumber: 'LBR-FILT', name: 'Filter Installation', category: 'Labor', subcategory: 'Installation', price: 275.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-007', heritageNumber: 'LBR-HEAT', name: 'Heater Installation', category: 'Labor', subcategory: 'Installation', price: 650.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-008', heritageNumber: 'LBR-AUTO', name: 'Automation Installation', category: 'Labor', subcategory: 'Installation', price: 450.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-009', heritageNumber: 'LBR-SALT', name: 'Salt System Installation', category: 'Labor', subcategory: 'Installation', price: 375.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-010', heritageNumber: 'LBR-LITE', name: 'Light Installation', category: 'Labor', subcategory: 'Installation', price: 225.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-011', heritageNumber: 'LBR-MOTR', name: 'Motor Replacement', category: 'Labor', subcategory: 'Replacement', price: 175.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-012', heritageNumber: 'LBR-SEAL', name: 'Seal Replacement', category: 'Labor', subcategory: 'Replacement', price: 95.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-013', heritageNumber: 'LBR-CART', name: 'Cartridge Replacement', category: 'Labor', subcategory: 'Replacement', price: 75.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-014', heritageNumber: 'LBR-GRIDS', name: 'DE Grid Replacement', category: 'Labor', subcategory: 'Replacement', price: 150.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-015', heritageNumber: 'LBR-SAND', name: 'Sand Change', category: 'Labor', subcategory: 'Replacement', price: 225.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-016', heritageNumber: 'LBR-VALVE', name: 'Valve Installation', category: 'Labor', subcategory: 'Installation', price: 125.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-017', heritageNumber: 'LBR-PLUMB', name: 'Plumbing Repair (per hour)', category: 'Labor', subcategory: 'Hourly', price: 115.00, unit: 'HR', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-018', heritageNumber: 'LBR-LEAK', name: 'Leak Detection', category: 'Labor', subcategory: 'Service', price: 295.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-019', heritageNumber: 'LBR-DIAG', name: 'Equipment Diagnostic', category: 'Labor', subcategory: 'Service', price: 125.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-020', heritageNumber: 'LBR-STARTUP', name: 'Pool Startup Service', category: 'Labor', subcategory: 'Service', price: 195.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-021', heritageNumber: 'LBR-CLOSE', name: 'Pool Winterization', category: 'Labor', subcategory: 'Service', price: 245.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-022', heritageNumber: 'LBR-ACID', name: 'Acid Wash', category: 'Labor', subcategory: 'Service', price: 495.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-023', heritageNumber: 'LBR-DRAIN', name: 'Pool Drain and Refill', category: 'Labor', subcategory: 'Service', price: 395.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-024', heritageNumber: 'LBR-TILE', name: 'Tile Cleaning', category: 'Labor', subcategory: 'Service', price: 295.00, unit: 'EA', manufacturer: 'Breakpoint' },
  { sku: 'LABOR-025', heritageNumber: 'LBR-STAIN', name: 'Stain Treatment', category: 'Labor', subcategory: 'Service', price: 195.00, unit: 'EA', manufacturer: 'Breakpoint' },
];

export function getProductsByCategory(category: HeritageCategory): HeritageProduct[] {
  return HERITAGE_PRODUCTS.filter(p => p.category === category);
}

export function searchProducts(query: string): HeritageProduct[] {
  const lower = query.toLowerCase();
  return HERITAGE_PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(lower) ||
    p.sku.toLowerCase().includes(lower) ||
    p.heritageNumber.toLowerCase().includes(lower) ||
    p.manufacturer.toLowerCase().includes(lower)
  );
}

export function getProductBySku(sku: string): HeritageProduct | undefined {
  return HERITAGE_PRODUCTS.find(p => p.sku === sku);
}

export function getSubcategories(category: HeritageCategory): string[] {
  const products = getProductsByCategory(category);
  return [...new Set(products.map(p => p.subcategory))];
}
